# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['@all']
   'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kcmutils': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/kdbusaddons': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'pim/libkgapi': '@latest-kf6'
    'third-party/qcoro': '@latest-kf6'

Options:
 test-before-installing: true
 require-passing-tests-on: ['@all']
